version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@5.0.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo "Hello World"
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: 'Running In a Unique Container'
          command: |
            node -v
